### ISSUE TITLE
Minor discrepancy in mask_out_artifacts docstring and code

### ISSUE THREAD

**Issue by jchutrue** [magland/ml_ephys#10]
The docstring for the mask_out_artifacts processor says a chunk and its neighbors are zeroed out if the RSS is above threshold: 
https://github.com/magland/ml_ephys/blob/65c2e820652b30eec40b5188937a072333ee6c3b/ml_ephys/preprocessing/p_mask_out_artifacts.py#L47-L48

However, the code indicates that it is **square root** of the RSS that is used to determine if a chunk should be zeroed out:
https://github.com/magland/ml_ephys/blob/65c2e820652b30eec40b5188937a072333ee6c3b/ml_ephys/preprocessing/p_mask_out_artifacts.py#L101

https://github.com/magland/ml_ephys/blob/65c2e820652b30eec40b5188937a072333ee6c3b/ml_ephys/preprocessing/p_mask_out_artifacts.py#L106-L116

Therefore a user who looked only at the output of `ml-spec` without inspecting the source code could choose incorrect parameters for this processor.

**Comment by magland** [comment]
Thanks for the report! I have changed the documentation on the master branch.
