### ISSUE TITLE
error in p_convert_array.py

### ISSUE THREAD

**Issue by khl02007** [magland/ml_ephys#3]
line 149 defines 'filebytes' only if 'ext_in' is the same as 'format_in' but this will never happen as it is written right now because 'ext_in' returns the extension of the input file with os.path.splitext and always begins with a '.' whereas 'format_in' does not (i.e. one would be comparing '.dat' to 'dat'). as a result 'filebytes' does not get defined and one gets a UnboundLocalError. I changed 'if ext_in == format_in:' to 'if ext_in[1:] == format_in:' and this seems to work.

**Comment by alexmorley** [comment]
actually the logic there is wrong regardless. that was my fault. will fix now.

**Comment by alexmorley** [comment]
pushed a fix, will leave this issue open until I've added a test!

**Comment by tjd2002** [comment]
Fixed in https://github.com/magland/ml_ephys/commit/8e332729dccebb5e5190d48ca7af762687c62ecc
